#!/usr/bin/env node
// Token transformer for @hypermedia-components/core.
//
// Reads DTCG-shaped JSON sources from src/tokens, resolves `{a.b.c}`
// references across the four token layers, and emits dist/hc.tokens.css
// with `--hc-*` custom properties wrapped in `@layer hc.tokens`.
//
// Output rules
// - Each top-level token file becomes one selector block.
// - Variable names drop the file's namespace and join the remaining JSON
//   path with hyphens, prefixed with `--hc-`. Example:
//     semantic.tokens.json -> color.action.primary.bg
//       -> --hc-color-action-primary-bg
//     component.tokens.json -> button.primary.bg
//       -> --hc-button-primary-bg
// - primitive.tokens.json is loaded for reference resolution only; its
//   values are not emitted.
//
// The transformation is exported as buildTokensCss({ sources, trees })
// for testing; the CLI block at the bottom wires it up to disk I/O.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const REF_RE = /^\{([^}]+)\}$/;

function isTokenLeaf(node) {
  return node && typeof node === 'object' && '$value' in node;
}

/** Walk a token tree; call cb(path, leaf) for every token leaf. */
function walkLeaves(node, path, cb) {
  if (!node || typeof node !== 'object') return;
  if (isTokenLeaf(node)) {
    cb(path, node);
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    walkLeaves(child, path.concat(key), cb);
  }
}

/** Build a flat map: "namespace.dot.path" -> raw $value (string). */
function indexTokens(sources, trees) {
  const map = new Map();
  for (const src of sources) {
    walkLeaves(trees[src.namespace], [], (path, leaf) => {
      const key = [src.namespace, ...path].join('.');
      map.set(key, String(leaf.$value));
    });
  }
  return map;
}

/** Resolve `{ref}` (whole-value) and any inline `{ref}` substrings. */
function resolveValue(raw, table, stack = []) {
  const fullMatch = raw.match(REF_RE);
  if (fullMatch) {
    const ref = fullMatch[1];
    if (stack.includes(ref)) {
      throw new Error(`Circular token reference: ${[...stack, ref].join(' -> ')}`);
    }
    const target = table.get(ref);
    if (target == null) {
      throw new Error(`Unknown token reference: {${ref}}`);
    }
    return resolveValue(target, table, [...stack, ref]);
  }
  // Allow embedded refs like `0 0 0 2px {semantic.color.focus-ring}` later.
  return raw.replace(/\{([^}]+)\}/g, (_, ref) => {
    const target = table.get(ref);
    if (target == null) throw new Error(`Unknown token reference: {${ref}}`);
    return resolveValue(target, table, [...stack, ref]);
  });
}

function cssVarName(jsonPath) {
  return '--hc-' + jsonPath.join('-');
}

function emitBlock(selector, lines) {
  return `${selector} {\n${lines.map((l) => '  ' + l).join('\n')}\n}\n`;
}

/**
 * Build the hc.tokens.css text from in-memory token trees.
 *
 * @param {Object} opts
 * @param {Array<{namespace: string, selector?: string, emit?: boolean}>} opts.sources
 *   Ordered list of token layers. Sources with `emit: false` only feed
 *   reference resolution; their values are never written.
 * @param {Record<string, unknown>} opts.trees
 *   Parsed token trees keyed by namespace.
 * @returns {{ css: string, varCount: number, blockCount: number }}
 */
export function buildTokensCss({ sources, trees }) {
  const table = indexTokens(sources, trees);

  const blocks = [];
  for (const src of sources) {
    if (src.emit === false) continue;
    const lines = [];
    walkLeaves(trees[src.namespace], [], (path, leaf) => {
      const name = cssVarName(path);
      const value = resolveValue(String(leaf.$value), table);
      lines.push(`${name}: ${value};`);
    });
    if (lines.length === 0) continue;
    blocks.push(emitBlock(src.selector, lines));
  }

  const banner =
    '/* Generated by packages/core/scripts/build-tokens.mjs. Do not edit by hand. */\n';
  const css =
    banner +
    '@layer hc.tokens {\n' +
    blocks.map((b) => b.replace(/^/gm, '  ').replace(/^ {2}$/gm, '')).join('\n') +
    '}\n';

  // Count declarations only — `--hc-foo:` lines. Skip occurrences of
  // `--hc-` inside `var()` references on the right-hand side.
  const varCount = blocks.reduce((n, b) => n + (b.match(/--hc-[a-z0-9-]+:/g)?.length ?? 0), 0);
  return { css, varCount, blockCount: blocks.length };
}

// CLI default. Files and their output selectors. `emit: false` means
// values are loaded into the resolution table but never written to CSS.
export const DEFAULT_SOURCES = [
  { namespace: 'primitive', file: 'primitive.tokens.json', emit: false },
  { namespace: 'semantic',  file: 'semantic.tokens.json',  selector: ':root, [data-theme="light"]' },
  { namespace: 'component', file: 'component.tokens.json', selector: ':root' },
  { namespace: 'theme.dark', file: 'theme.dark.tokens.json', selector: '[data-theme="dark"]' },
  // Density layers override --hc-control-* at runtime via the
  // data-density attribute. Components that should respond to density
  // (button, input) reference --hc-control-* through a `var()`
  // indirection in their own tokens — see component.tokens.json.
  { namespace: 'density.comfortable', file: 'density.comfortable.tokens.json', selector: ':root, [data-density="comfortable"]' },
  { namespace: 'density.compact',     file: 'density.compact.tokens.json',     selector: '[data-density="compact"]' },
  { namespace: 'density.dense',       file: 'density.dense.tokens.json',       selector: '[data-density="dense"]' },
];

async function main() {
  const here = dirname(fileURLToPath(import.meta.url));
  const pkgRoot = resolve(here, '..');
  const tokensDir = join(pkgRoot, 'src', 'tokens');
  const distDir = join(pkgRoot, 'dist');

  const trees = {};
  for (const src of DEFAULT_SOURCES) {
    const text = await readFile(join(tokensDir, src.file), 'utf8');
    trees[src.namespace] = JSON.parse(text);
  }

  const { css, varCount, blockCount } = buildTokensCss({
    sources: DEFAULT_SOURCES,
    trees,
  });

  await mkdir(distDir, { recursive: true });
  await writeFile(join(distDir, 'hc.tokens.css'), css, 'utf8');

  console.log(`hc.tokens.css written (${varCount} vars across ${blockCount} blocks)`);
}

// Run main only when invoked as a script (not when imported by tests).
const invokedAsScript =
  typeof process !== 'undefined' &&
  process.argv[1] &&
  fileURLToPath(import.meta.url) === resolve(process.argv[1]);

if (invokedAsScript) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
