import { execFileSync } from 'node:child_process';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, it, expect } from 'vitest';
import { listEmailFragments, ejectEmail, EMAIL_FILES } from '../lib/email.mjs';

const BIN = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'bin', 'hc-cli.mjs');

let dir;
beforeEach(async () => {
  dir = await mkdtemp(join(tmpdir(), 'hc-cli-email-'));
});
afterEach(async () => {
  await rm(dir, { recursive: true, force: true });
});

function run(...args) {
  try {
    const stdout = execFileSync(process.execPath, [BIN, ...args], { encoding: 'utf8' });
    return { code: 0, stdout, stderr: '' };
  } catch (error) {
    return { code: error.status, stdout: error.stdout ?? '', stderr: error.stderr ?? '' };
  }
}

describe('listEmailFragments', () => {
  it('lists every fragment and partial with its contract purpose', async () => {
    const frags = await listEmailFragments();
    const names = frags.map((f) => f.name);
    expect(names).toContain('button');
    expect(names).toContain('layout');
    expect(names).toHaveLength(12);
    const button = frags.find((f) => f.name === 'button');
    expect(button.purpose).toContain('button');
  });
});

describe('ejectEmail', () => {
  it('writes the three files, themed and fully resolved', async () => {
    const written = await ejectEmail({ dir });
    expect(written).toHaveLength(EMAIL_FILES.length);
    for (const name of EMAIL_FILES) {
      expect(existsSync(join(dir, 'email', name)), name).toBe(true);
    }
    const fragments = await readFile(join(dir, 'email', 'hc-email.html'), 'utf8');
    expect(fragments).toContain('th:fragment="hcButton(href, label)"');
    expect(fragments).toContain('Generated by @hypermedia-components/core');
    expect(fragments).toContain('Regenerate: npx @hypermedia-components/cli email eject');
    expect(fragments).not.toMatch(/(?<!\$)\{[a-z0-9][a-z0-9-]*(\.dark)?\}/);
    expect(fragments).not.toContain('var(');

    const layout = await readFile(join(dir, 'email', 'hc-email-layout.html'), 'utf8');
    expect(layout).toContain('<style>');
    expect(layout).toContain('prefers-color-scheme: dark');

    const tokens = JSON.parse(await readFile(join(dir, 'email', 'email-tokens.json'), 'utf8'));
    expect(tokens.light['button-primary-bg']).toMatch(/^#/);
    expect(tokens.dark['color-bg']).not.toBe(tokens.light['color-bg']);
  });

  it('plain flavor strips Thymeleaf attributes', async () => {
    await ejectEmail({ dir, flavor: 'plain' });
    const fragments = await readFile(join(dir, 'email', 'hc-email.html'), 'utf8');
    expect(fragments).not.toMatch(/(?:th|xmlns):[a-z-]+="/);
  });

  it('axes theme the output', async () => {
    await ejectEmail({ dir });
    const stock = JSON.parse(await readFile(join(dir, 'email', 'email-tokens.json'), 'utf8'));
    await ejectEmail({ dir: join(dir, 'themed'), color: 'teal', neutral: 'slate' });
    const themed = JSON.parse(
      await readFile(join(dir, 'themed', 'email', 'email-tokens.json'), 'utf8'),
    );
    expect(themed.light['button-primary-bg']).not.toBe(stock.light['button-primary-bg']);
    const fragments = await readFile(join(dir, 'themed', 'email', 'hc-email.html'), 'utf8');
    expect(fragments).toContain(themed.light['button-primary-bg']);
  });

  it('applies a theme-builder accent export via --tokens', async () => {
    const custom = join(dir, 'custom.tokens.json');
    await writeFile(
      custom,
      JSON.stringify({
        color: { action: { primary: { bg: { $type: 'color', $value: '#123456' } } } },
      }),
    );
    await ejectEmail({ dir, tokensFile: custom });
    const fragments = await readFile(join(dir, 'email', 'hc-email.html'), 'utf8');
    expect(fragments).toContain('background-color:#123456');
    expect(fragments).toContain('(+ custom token overrides)');
  });

  it('applies a full-theme patch export via --tokens', async () => {
    const custom = join(dir, 'patch.tokens.json');
    await writeFile(
      custom,
      JSON.stringify({
        semantic: { color: { bg: { $type: 'color', $value: '#fafafa' } } },
        'theme.dark': { color: { bg: { $type: 'color', $value: '#010203' } } },
      }),
    );
    await ejectEmail({ dir, tokensFile: custom });
    const tokens = JSON.parse(await readFile(join(dir, 'email', 'email-tokens.json'), 'utf8'));
    expect(tokens.light['color-bg']).toBe('#fafafa');
    expect(tokens.dark['color-bg']).toBe('#010203');
  });

  it('refuses to overwrite without force, overwrites with force', async () => {
    await ejectEmail({ dir });
    await expect(ejectEmail({ dir })).rejects.toThrow(/Refusing to overwrite/);
    await ejectEmail({ dir, force: true });
  });

  it('rejects unknown axes and flavors', async () => {
    await expect(ejectEmail({ dir, color: 'indigo' })).rejects.toThrow(/Unknown color/);
    await expect(ejectEmail({ dir, neutral: 'sand' })).rejects.toThrow(/Unknown neutral/);
    await expect(ejectEmail({ dir, flavor: 'mjml' })).rejects.toThrow(/Unknown flavor/);
  });
});

describe('bin: email', () => {
  it('email list prints the fragments', () => {
    const { code, stdout } = run('email', 'list');
    expect(code).toBe(0);
    expect(stdout).toContain('button');
    expect(stdout).toContain('layout');
  });

  it('email eject writes into <dir>/email/ and reports the files', () => {
    const { code, stdout } = run('email', 'eject', '--dir', dir, '--neutral', 'slate');
    expect(code).toBe(0);
    expect(stdout).toContain('Wrote 3 files');
    expect(existsSync(join(dir, 'email', 'hc-email.html'))).toBe(true);
  });

  it('email eject exits 2 on refusal', () => {
    expect(run('email', 'eject', '--dir', dir).code).toBe(0);
    expect(run('email', 'eject', '--dir', dir).code).toBe(2);
  });

  it('unknown email subcommand exits 1 with usage', () => {
    const { code, stderr } = run('email', 'nope');
    expect(code).toBe(1);
    expect(stderr).toContain('Unknown email subcommand');
  });
});
